spring.datasource.url=jdbc:postgresql://localhost:5432/poupanca_db
spring.datasource.username=postgres
spring.datasource.password=12072082Ry!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
